### ISSUE TITLE
Mapping axes on thumbsticks

### ISSUE THREAD

**Issue by n3veruary** [ZGako/sf6-input-history#1]
The tutorial isn't clear which codes should be used for thumbstick mapping. Can you let me know how I should interpret the output from a gamepad tester into button codes?

**Comment by ZGako** [comment]
So originally the code was made with people who used the D-PAD in mind, which also included hitbox/arcade stick since those map to the d-pad too.

If what you mean by thumbstick is the analog stick, then it is not yet supported. Let me know if this is indeed what you mean so I could try to implement it as a new feature.

**Comment by n3veruary** [comment]
Hi,

Yes, I meant the analog stick.

**Comment by ZGako** [comment]
I see.
Though I'm not home rn I could try to implement it on my laptop this evening.

**Comment by ZGako** [comment]
So I've tried implementing the feature on a different branch, if you're willing you could test it out, I believe it should work out of the box since analog mapping should be the same for each controller.
Only problem you may have is changing the deadzone on the controller, as I've set it to a random amount considering I'm not too familiar with gamepads.

link: https://github.com/ZGako/sf6-input-history/tree/analog-stick-implementation

If there's any problems feel free to report them here :)

**Comment by n3veruary** [comment]
Hi,

This appears to work conceptually. Some notes:

1) As written, this was throwing type errors due to const instead of let on Line 340 (due to re-assigning "angle" shortly after declaration). I attempted to correct this on my end by changing const to let.
2) After the above correction was made, I observed the following behavior on the buttons and left analog stick:
- All assigned attack buttons and macros (specifically MP+MK, HP+HK, MP+HP, MK+HK) behaved as expected
- Neutral displays as right
- Down displays as up
- Up displays as neutral
- Left displays as left
- Right displays as right
- Up+Left displays as neutral
- Up+Right displays as neutral
- Down+Left displays as neutral
- Down+Right displays as neutral

I'm using a Hori fighting commander octa in PC mode for these tests. I noticed that in PS5 mode, the gamepad tester linked in the readme seems to read Button 11 but also an axis input. PS5 or PC mode does not affect performance in SF6, so swapping to PC mode for the sake of this feature is acceptable.

Let me know if there is any other info I can provide.

**Comment by ZGako** [comment]
I'm guessing the main issue here is that I forgot to consider the deadzone correctly, I probably should change how the value gets interpreted or simply put a one dimensional deadzone. (Basically I checked if axis < deadzone but forgetting that diagonals are capped at 0.7, which is almost the deadzone).

I would actually ask you for feedback regarding deadzones.
Usually are they for both axis? If not what is usually the range and the default values for it.

While you're at it maybe you could try to check if lowering the deadzones actually makes the thing work.

I'll only be back home in 3/4 days where I should be able to get a gamepad working (ps2 one but oh well) and test it, but I'd like to make the thing work before then.

**Comment by ZGako** [comment]
As for the PS5 mode button 11 and axis thing, I don't think I understood whether pressing button 11 also triggered an axis movement or the other way around.

In any case I'd probably ask for specific feedback on that issue once I make the actual thing work.

I found an app that lets you turn your phone into a controller so I'll try debugging the app with that later on and make it work later today.

**Comment by ZGako** [comment]
Ok so I believe I made it fully work since I tested it with a gamepad phone app. 
if you confirm it fully works with a real controller I'll do a full release. (you may seem further commits to fix some stuff with non mapped button resetting history stuff)

**Comment by n3veruary** [comment]
Hello,

This is throwing another type error on my end:

TypeError: Cannot read properties of undefined (reading 'pressed')
at updateStatus (line 286).

This variable looks properly defined. I'm not sure what the issue is here.

**Comment by ZGako** [comment]
Could be some of the changes I've made for the unmapped buttons things, I'll check asap

**Comment by ZGako** [comment]
Ok so one possibility is that now I loop through the mapped codes directly rather than all the gamepad buttons (to remove unbinded buttons resetting the input history). You may have some codes that don't bind to a correct button or unused binds not set at -1

I say this cuz I'm not getting the same error myself

**Comment by ZGako** [comment]
For the record I did disable the analog config from the latest config file to prep it for release

**Comment by n3veruary** [comment]
Hi,

This works! Everything appears to be working as expected, but obvious most people's mileage may vary re: deadzones. Probably worth collecting more data on controllers overall.
